  name: Deploy Go Backend

  on:
    push:
      branches:
        - master
      paths:
        - 'backend-go/**'
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
        packages: write
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./backend-go
            push: true
            tags: ghcr.io/${{ github.repository }}:latest
        - name: Deploy to server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              # Nettoyer les anciens containers
              docker stop adminer save_your_car_db go-backend || true
              docker rm adminer save_your_car_db go-backend || true
                    
              # Créer le réseau
              docker network rm app-network || true
              docker network create app-network
                    
              # PostgreSQL
              docker run -d \
                --name save_your_car_db \
                --network app-network \
                --restart always \
                -e POSTGRES_USER=${DB_USER} \
                -e POSTGRES_PASSWORD=${DB_PASSWORD} \
                -e POSTGRES_DB=${DB_NAME} \
                -e POSTGRES_HOST_AUTH_METHOD=md5 \
                -v postgres_data:/var/lib/postgresql/data \
                -p 5432:5432 \
                postgres:15-alpine
                    
              # Attendre PostgreSQL
              sleep 15
                    
              # Adminer
              docker run -d \
                --name adminer \
                --network app-network \
                --restart always \
                -p 8080:8080 \
                adminer
                    
              # Backend
              docker pull ghcr.io/${{ github.repository }}:latest
              docker run -d \
                --name go-backend \
                --network app-network \
                -p 3334:3334 \
                --restart always \
                --env-file ~/save_cour_car_recovery/.env \
                ghcr.io/${{ github.repository }}:latest