name: Deploy Go Backend

on: 
  push:
    branches:
      - master
    paths:
      - 'backend-go/**' # Se déclenche uniquement si le code du backend change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend-go # Le contexte est le sous-dossier backend-go
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/save_cour_car_recovery:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/save_cour_car_recovery:latest
            docker stop go-backend || true
            docker rm go-backend || true
            docker run -d \
              --name go-backend \
              -p 3334:3334 \
              --restart always \
              --env-file ~/save_cour_car_recovery/.env \
              ${{ secrets.DOCKERHUB_USERNAME }}/save_cour_car_recovery:latest